Added cosmetic changes

diff --git a/run/install b/run/install
--- a/run/install
+++ b/run/install
@@ -2,13 +2,32 @@
 
 # `install` Run all installers
 
-set -e
-
 cd $DOT
 
-echo "› Run all installers"
-find ./rel -name install.sh
-printf "\n"
+set -e
 
-echo "› Start"
+info () {
+  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
+}
+
+user () {
+  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
+}
+
+success () {
+  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+}
+
+fail () {
+  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
+  echo ''
+  exit
+}
+
+info "Run following installers"
+find ./rel -name install.sh
+echo ''
+
+info "Start"
 find ./rel -name install.sh -exec sh -c "{}" \;
+echo ''
